// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkbv6qwWjcPG3KTDZqHiw2grnEzGolB_4',
    appId: '1:715756584047:web:9b9a0cdd928d59e1b5a19a',
    messagingSenderId: '715756584047',
    projectId: 'backtoschool-121c9',
    authDomain: 'backtoschool-121c9.firebaseapp.com',
    storageBucket: 'backtoschool-121c9.appspot.com',
    measurementId: 'G-9NDH73VZVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJdRLmveyQyGx1xwfZVuEYsOWAhuCEfnE',
    appId: '1:715756584047:android:11d783782194ba03b5a19a',
    messagingSenderId: '715756584047',
    projectId: 'backtoschool-121c9',
    storageBucket: 'backtoschool-121c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOE6CL-1O-CEWH7g5GFqigyWSS3gHQyho',
    appId: '1:715756584047:ios:b65994da88c88e51b5a19a',
    messagingSenderId: '715756584047',
    projectId: 'backtoschool-121c9',
    storageBucket: 'backtoschool-121c9.appspot.com',
    iosBundleId: 'com.example.backToSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOE6CL-1O-CEWH7g5GFqigyWSS3gHQyho',
    appId: '1:715756584047:ios:b65994da88c88e51b5a19a',
    messagingSenderId: '715756584047',
    projectId: 'backtoschool-121c9',
    storageBucket: 'backtoschool-121c9.appspot.com',
    iosBundleId: 'com.example.backToSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkbv6qwWjcPG3KTDZqHiw2grnEzGolB_4',
    appId: '1:715756584047:web:74291b5c104eb61cb5a19a',
    messagingSenderId: '715756584047',
    projectId: 'backtoschool-121c9',
    authDomain: 'backtoschool-121c9.firebaseapp.com',
    storageBucket: 'backtoschool-121c9.appspot.com',
    measurementId: 'G-RB082C5TFV',
  );
}
